name: EasyRBAC-CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build easyRBAC/easyRBAC.sln --configuration Release
      run: dotnet publish .\easyRBAC\src\EasyRbac.Web\ -c Release  --self-contained -r linux-x64
      run: rm -f ./easyRBAC/src/EasyRbac.Web/bin/Release/netcoreapp2.2/linux-x64/publish/appsettings.*
      run: rm -f ./easyRBAC/src/EasyRbac.Web/bin/Release/netcoreapp2.2/linux-x64/publish/*.pdb
      rum: tar -czvf easyRBAC.tar.gz easyRBAC/src/EasyRbac.Web/bin/Release/netcoreapp2.2/linux-x64/publish
