name: EasyRBAC-CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: |
        sh ./.github/workflows/build.sh
    - name: Push Result To Server
      uses: garygrossgarten/github-action-scp@release
      env:
        privateKey : ${{ secrets.SERVER_SSH_KEY }}
        local: "./easyRBAC.tar.gz"
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        remote: ${{ secrets.REMOTE_TARGET }}